### ISSUE TITLE
LOG and INFO file on Windows

### ISSUE THREAD

**Issue by g-rusev** [corvus-ch/rabbitmq-cli-consumer#21]
Hello,
Could not find a way to disable the following two logs in the config file - info and log.

I am Running the consumer this way:
rabbitmq-cli-consumer.exe -c rconfig.conf --executable "PHP.EXE consumer.php"

In the  config file always expect a valid windows file name.
Setting the info to blank string "" does not helped.
Commenting the both keys did not helped either.

How can I turn off logging ?

**Comment by corvus-ch** [comment]
When providing the `--verbose, -V` option, the log section in the configuration becomes optional. The `--verbose` option will result in the logs written to STDOUT and STDERR which you can redirect to `NUL` or `$NULL` depending on the shell you are using. I am not familiar with Windows but his is what I get from https://stackoverflow.com/questions/313111/dev-null-in-windows.

**Comment by corvus-ch** [comment]
I assume that my previous answered the question. Therefore I close this issue. If this is premature, feel free to ask for a reopen.
