### ISSUE TITLE
$GOPATH not set. For more details see: go help gopath

### ISSUE THREAD

**Issue by grekpg** [corvus-ch/rabbitmq-cli-consumer#23]
i get error in ubuntu 

```
 go get github.com/corvus-ch/rabbitmq-cli-consumer
package github.com/corvus-ch/rabbitmq-cli-consumer: cannot download, $GOPATH not set. For more details see: go help gopath
```

please update install inctruction i dont know go.
thanks

**Comment by corvus-ch** [comment]
The documentation of this project assume one knows how to setup a local Golang workspace according to [the official documentation](https://golang.org/doc/code.html). 

For further help please seek out for introduction tutorials about Golang and or try one of the many friendly places in the internet dedicated to help beginners.

**Comment by grekpg** [comment]
Thanks for reply, did You provide binaries like https://github.com/ricbra/rabbitmq-cli-consumer/releases ? 
i install golang for unbuntu 16.04 from repo but still have 

```
go get github.com/corvus-ch/rabbitmq-cli-consumer
# github.com/streadway/amqp
/home/grek/go/src/github.com/streadway/amqp/uri.go:75: u.Hostname undefined (type *url.URL has no field or method Hostname)
/home/grek/go/src/github.com/streadway/amqp/uri.go:76: u.Port undefined (type *url.URL has no field or method Port)
/home/grek/go/src/github.com/streadway/amqp/uri.go:161: authority.RawPath undefined (type *url.URL has no field or method RawPath)
```

**Comment by corvus-ch** [comment]
As stated in the [README](https://github.com/corvus-ch/rabbitmq-cli-consumer#binary), there are binary releases to be found at [the usual place for a project on Github](https://github.com/corvus-ch/rabbitmq-cli-consumer/releases).

Please notice that [CONTRIBUTING.md](https://github.com/corvus-ch/rabbitmq-cli-consumer/blob/master/CONTRIBUTING.md) states that this issue queue is for bug reports and feature requests  only.
