### ISSUE TITLE
Supervisord doesn't start the worker when I use the --pipe option

### ISSUE THREAD

**Issue by man0l** [corvus-ch/rabbitmq-cli-consumer#35]
I am invoking the worker with this command

`rabbitmq-cli-consumer -e "/usr/bin/php app/console worker:multivariation_products:fetch:save --env=prod" -c rabbit/proceed_parsed_multivariation_product.conf.dist --pipe
`

My rabbitmq configuration is 
```

[rabbitmq]
host = <host>
username = <user>
password = <pass>
vhost=/
port=5672
queue=send_parsed_multivariation_product_queue
compression=On

[prefetch]
count=1
global=Off

[exchange]
name=send_parsed_multivariation_product
type=fanout
autodelete=Off
durable=On

[logs]
error = /tmp/send_parsed_multivariation_product_error.log
info = /tmp/send_parsed_multivariation_product_info.log
```

When I start the command manually, it works great, but the supervisor deamon could not start the process. 

Can somebody help me with this issue?

**Comment by corvus-ch** [comment]
Hi @man0l,

Have you checked the logs of Supervidord? They usually contain the details if stuff like this is happening (might be dependent on severity levels). And can you please provide the exact Supervisord configuration you are using?

**Comment by man0l** [comment]
Hi @corvus-ch,
Thank you for suggesting me to look again in the log. I've changed the supervisor's log level to debug and I found out that I am reffering to the previous rabbitmq-cli-consumer version which does not sppoprt --pipe option. It's configuration bug on my side.

So I am closing this issue because it's not relevant.

Thank you for your help,
Regards,
Manol.
