### ISSUE TITLE
No log for bash/shell executable

### ISSUE THREAD

**Issue by bappr** [corvus-ch/rabbitmq-cli-consumer#39]
Hello,

Does the consumer only work with php executable?

=>
`rabbitmq-cli-consumer -V -e "echo RECEIVED" -i -u amqp://$RABBIT_USER:$RABBIT_PWD@$RABBIT_HOST -q $RABBIT_QUEUE`

Logs never show up in STDOUT/STDERR/FILE whatever the config when using a bash/shell script.

Thanks for your help

**Comment by corvus-ch** [comment]
You are missing the `--output, -o` option. When set, the output of the executable (any executable including shell scripts) is captured and logged by `rabbitmq-cli-consumer`.

**Comment by bappr** [comment]
Don't know how I manage to miss this huge flag...
Thanks a lot.

**Comment by Gingonic** [comment]
@corvus-ch Sorry to reopen this issue but shouldn't  the following sentence in the README include that the flag "--output" is necessary as it implies a default behavior that is not true?
"All logs, including the output of the called executable, will be available in STDOUT/STDERR.". 

I tested this Version 2.3.3
