### ISSUE TITLE
Graceful shutdown doesn't work properly

### ISSUE THREAD

**Issue by salvatorecordiano** [corvus-ch/rabbitmq-cli-consumer#51]
After solving #40, when we send to the consumer `SIGTERM`, it doesn't handle the signal in the right way.

When `SIGTERM` is received, it stops consuming new messages, but the consumer process will not terminate.

### How to reproduce the bug

RabbitMQ server is up and running and the queue `my-queue` is always empty.

#### Step 1 - Check if consumer is running

```
$ ps -ef | grep "rabbitmq-cli-consumer" | grep -v grep | wc -l
0
```

No consumer is running here.

#### Step 2 - Start consumer

```
/var/www/project/bin/rabbitmq-cli-consumer -e /var/www/project/bin/my-executable -q my-queue -c /var/www/project/consumer.conf -i -o
```

#### Step 3 - Send `SIGTERM` to the consumer process

In a new terminal window:

```
ps -ef | grep "rabbitmq-cli-consumer" | grep -v grep | awk '{print $1}' | xargs --no-run-if-empty kill
sleep 10
```

#### Step 4 - Check if consumer is running

```
$ ps -ef | grep "rabbitmq-cli-consumer" | grep -v grep | wc -l
1
```

The consumer is running here.

If I do the previous procedure with consumer version `2.2.0` the step 4 result is 0, as expected.

**Comment by salvatorecordiano** [comment]
@corvus-ch are you able to reproduce my bug?

**Comment by salvatorecordiano** [comment]
Well done @corvus-ch!
I suggest you to delete the last release on GitHub, so we don't break things to other users.
Furthermore, if you publish an alpha release i will do a test for you.

**Comment by corvus-ch** [comment]
A pre release build is available at https://github.com/corvus-ch/rabbitmq-cli-consumer/releases/tag/2.3.2-alpha1. Work on a fix is happening at #52.

**Comment by salvatorecordiano** [comment]
@corvus-ch I tested in my local environment your build and it works in the right way.

**Comment by corvus-ch** [comment]
I am glad the problem got fixed. Meanwhile, I am still looking for a way to get this appropriately covered by automated tests.

**Comment by corvus-ch** [comment]
I did some refactoring to remove a troublesome design decision I previously made. I am now confident, the issue in question is captured by tests. There is a new pre release build available: https://github.com/corvus-ch/rabbitmq-cli-consumer/releases/tag/2.3.2-alpha2.

@salvatorecordiano Do you mind to give the alpha2 a try?

If that one works for you. I will finish this up and make a new regular release.

**Comment by salvatorecordiano** [comment]
@corvus-ch I tried it and it works in the right way

**Comment by corvus-ch** [comment]
New release is available: https://github.com/corvus-ch/rabbitmq-cli-consumer/releases/tag/2.3.2.
